//generate random data
//author: printf83@gmail.com (c) 2020 - 2021

(function ($) {
	var tname_b = [
		"Ben",
		"Sammie",
		"Darryl",
		"Mohammad",
		"Felton",
		"Neville",
		"Ward",
		"Len",
		"Ethan",
		"Fredric",
		"Chang",
		"Ira",
		"Robby",
		"Austin",
		"Cletus",
		"Everette",
		"Freeman",
		"Byron",
		"Ismael",
		"Lino",
		"Hobert",
		"Odell",
		"Valentin",
		"Gil",
		"Van",
		"Sydney",
		"Hipolito",
		"Arnold",
		"Donte",
		"Drew",
		"Dewayne",
		"Mike",
		"Brent",
		"Carlos",
		"Bennett",
		"Mario",
		"Chet",
		"Davis",
		"Ramon",
		"Efrain",
		"Rayford",
		"Fred",
		"Emmitt",
		"Willian",
		"Marcelo",
		"Cornell",
		"Gustavo",
		"Scotty",
		"Pete",
		"Edward",
		"Jean",
		"Albert",
		"Carlo",
		"Joel",
		"Rolf",
		"Chadwick",
		"Rashad",
		"Kareem",
		"Seymour",
		"Marion",
		"Andre",
		"Quinton",
		"Marty",
		"Jarrod",
		"Allan",
		"Cedrick",
		"Heath",
		"Ned",
		"Harrison",
		"Matt",
		"Loyd",
		"Jefferson",
		"Fidel",
		"Len",
		"Brandon",
		"Curt",
		"Johnie",
		"Pasquale",
		"Francisco",
		"Drew",
		"Roberto",
		"Micah",
		"Carrol",
		"Fritz",
		"Vince",
		"Chance",
		"Simon",
		"Dane",
		"Randell",
		"Weldon",
		"Milton",
		"Gail",
		"Patricia",
		"Wilson",
		"Edgar",
		"Darrel",
		"Anderson",
		"Sandy",
		"Armand",
		"Mikel",
		"Burton",
		"Bernardo",
		"Neal",
		"Tracy",
		"Vern",
		"Barry",
		"James",
		"Brain",
		"Sergio",
		"Gregorio",
		"Sean",
		"Rupert",
		"Alejandro",
		"Kasey",
		"Marcellus",
		"Arnold",
		"Garland",
		"Clement",
		"Lloyd",
		"August",
		"Raleigh",
		"Art",
		"Otto",
		"Robbie",
		"Chadwick",
		"Hugo",
		"Odell",
		"Darrin",
		"Hershel",
		"Mohammed",
		"Gerry",
		"Ramiro",
		"Cristobal",
		"Ambrose",
		"Wilson",
		"Eugenio",
		"Wes",
		"Olen",
		"Dewey",
		"Cordell",
		"Lorenzo",
		"Prince",
		"Darrell",
		"Hayden",
		"Jerold",
		"Jordan",
		"Juan",
		"Jesse",
		"Thanh",
		"Aldo",
		"Alexander",
		"Bill",
		"Robin",
		"Dalton",
		"Terrance",
		"Cordell",
		"Quinton",
		"Raleigh",
		"Dallas",
		"Bert",
		"Titus",
		"Demarcus",
		"Brady",
		"Elvis",
		"Truman",
		"Hugh",
		"Sid",
		"Amos",
		"Jamel",
		"Tomas",
		"Rocco",
		"Gus",
		"Bradford",
		"Jarod",
		"Percy",
		"Horacio",
		"Robert",
		"Oren",
		"Bret",
		"Wilton",
		"Oscar",
		"Antonio",
		"Gregg",
		"Wilfredo",
		"Armand",
		"Barrett",
		"Everette",
		"Isaac",
		"Hershel",
		"Reginald",
		"Frank",
		"Kory",
		"Jeff",
		"Herschel",
		"Zachariah",
		"Charlie",
		"Ty",
		"Berry",
		"Connie",
		"Rickie",
	];

	var tname_g = [
		"Marjory",
		"Ok",
		"Hillary",
		"Helene",
		"Vinita",
		"Evelyne",
		"Shemika",
		"Larisa",
		"Vicenta",
		"Adelia",
		"Alline",
		"Annamaria",
		"Nicolle",
		"Iva",
		"Niesha",
		"Therese",
		"Janell",
		"Kerri",
		"Sasha",
		"Shawna",
		"Leighann",
		"Alexandra",
		"Lashandra",
		"Tammera",
		"Jeanette",
		"Maura",
		"Signe",
		"Bonnie",
		"Cassie",
		"Sherita",
		"Liberty",
		"Hannah",
		"Micha",
		"Charlyn",
		"Irmgard",
		"Elisabeth",
		"Rossana",
		"Tobie",
		"Lisbeth",
		"Keitha",
		"Yasmin",
		"Letha",
		"Kathi",
		"Janine",
		"Fernanda",
		"Marianela",
		"Mora",
		"Angelina",
		"Sophie",
		"Patrice",
		"Patria",
		"Maricela",
		"Shenita",
		"Yuette",
		"Rosetta",
		"Herma",
		"Kandra",
		"Voncile",
		"Terese",
		"Emely",
		"Flora",
		"Lynne",
		"Karole",
		"Regina",
		"Elfriede",
		"Delaine",
		"Hanh",
		"Candice",
		"Alysa",
		"Vi",
		"Tai",
		"Yukiko",
		"Noelle",
		"Marketta",
		"Tonia",
		"Lacey",
		"Maxine",
		"Venice",
		"Ashleigh",
		"Alice",
		"Lynell",
		"Danna",
		"Josephine",
		"Maye",
		"Keturah",
		"Lyn",
		"Lucina",
		"Georgina",
		"Verlie",
		"Idell",
		"Katherin",
		"Ela",
		"Luna",
		"Li",
		"Arlena",
		"Marylyn",
		"Lenita",
		"Manuela",
		"Allena",
		"Adah",
	];

	var t_email = ["@gmail.com", "@yahoo.com", "@live.com", "@outlook.com", "@aol.com", "@tm.com.my", "@kdn.gov.my"];

	$.rdata = {
		name: () => {
			if (ns.core.rndBetween(1, 100) > 50) {
				var fName = ns.core.rndBetween(0, tname_b.length - 1);
				var lName = ns.core.rndBetween(0, tname_b.length - 1);
				while (fName === lName) {
					fName = ns.core.rndBetween(0, tname_b.length - 1);
				}

				return [tname_b[fName], tname_b[lName]].join(" ");
			} else {
				var fName = ns.core.rndBetween(0, tname_g.length - 1);
				var lName = ns.core.rndBetween(0, tname_b.length - 1);

				return [tname_g[fName], tname_b[lName]].join(" ");
			}
		},
		email: (name) => {
			if (!name) {
				name = $.rdata.name();
			}

			var tname = name.split(" ");
			var tdiv = ns.core.rndBetween(0, 3);
			var temail = ns.core.rndBetween(0, t_email.length - 1);
			var tnum = ns.core.rndBetween(0, 100) > 50 ? ns.core.rndBetween(1, 9999) : "";
			var tdivcode = ["_", ".", "", "-"];
			return tname.join(tdivcode[tdiv]).toLowerCase() + tnum + t_email[temail];
		},
		phone: () => {
			return [
				"0",
				"1",
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(1, 9),
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(0, 9),
				ns.core.rndBetween(0, 9),
			].join("");
		},
		dob: () => {
			return [ns.core.rndBetween(1965, 2019), ns.core.pad(ns.core.rndBetween(1, 12), 2), ns.core.pad(ns.core.rndBetween(1, 28), 2)].join("-");
		},
		opt: (list) => {
			if (list && list.length > 0) {
				return list[ns.core.rndBetween(0, list.length - 1)].value;
			}
			return null;
		},
	};
})($);
